# https://docs.pytest.org/en/stable/customize.html
[tool.pytest.ini_options]
addopts = "--alluredir allure-results"
filterwarnings = "ignore::DeprecationWarning"
markers = [
    "register_page",
    "search_page",
    "main_page",
    "product_page",
    "login_page",
    "header_page",
    "footer_page",
    "comparison_page",
    "catalogue_page",
    "cart_page",
    "admin_page",
    "account_page"
    ]
