# https://docs.pytest.org/en/stable/customize.html
[tool.pytest.ini_options]
addopts = "--alluredir allure-results"
filterwarnings = "ignore::DeprecationWarning"
markers = [
    "register_page",
    "main_page",
    "admin_page",
    ]
